"""Data models for the trading bot."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class Signal(str, Enum):
    """Trading signal types."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TradeSignal(BaseModel):
    """A trading signal generated by an algorithm."""

    ticker: str
    signal: Signal
    algorithm: str
    strength: float = Field(ge=0.0, le=1.0, description="Signal strength from 0 to 1")
    price: float
    timestamp: datetime
    reason: str = ""


class AggregatedSignal(BaseModel):
    """An aggregated signal from multiple algorithms."""

    ticker: str
    signal: Signal
    buy_count: int = 0
    sell_count: int = 0
    hold_count: int = 0
    avg_strength: float = 0.0
    price: float = 0.0
    timestamp: datetime = Field(default_factory=datetime.now)
    contributing_signals: list[TradeSignal] = Field(default_factory=list)
    reasons: list[str] = Field(default_factory=list)


class Position(BaseModel):
    """A portfolio position."""

    ticker: str
    shares: float
    entry_price: float
    entry_date: datetime
    current_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0

    @property
    def market_value(self) -> float:
        """Current market value of the position."""
        return self.shares * self.current_price

    @property
    def cost_basis(self) -> float:
        """Total cost basis of the position."""
        return self.shares * self.entry_price

    @property
    def unrealized_pnl(self) -> float:
        """Unrealized profit/loss."""
        return self.market_value - self.cost_basis

    @property
    def unrealized_pnl_pct(self) -> float:
        """Unrealized profit/loss percentage."""
        if self.cost_basis == 0:
            return 0.0
        return (self.unrealized_pnl / self.cost_basis) * 100


class Trade(BaseModel):
    """A completed trade record."""

    ticker: str
    side: Signal
    shares: float
    price: float
    timestamp: datetime
    pnl: float = 0.0
    pnl_pct: float = 0.0


class PortfolioSnapshot(BaseModel):
    """A snapshot of the portfolio state."""

    timestamp: datetime
    cash: float
    positions: list[Position]
    total_value: float
    total_pnl: float
    total_pnl_pct: float
    trades: list[Trade] = Field(default_factory=list)
